// Levelsammlung.
//
// Textformat (siehe `level.js`):
//
//   .  leer          #  Blocker        o  Zielpunkt
//   >  < ^ v  Lichtquelle mit Strahlrichtung
//   /  \  drehbarer Spiegel            1  2  fester Spiegel („/“ bzw. „\“)
//
// `par` ist die vom Solver bestimmte Mindestzahl an Drehungen. Sie wird von
// `npm run check:lumen` gegengeprüft – ein falscher Wert ist ein Testfehler.

import { parseLevel } from './level.js';

export const levelDefs = [
  {
    id: 'l01',
    name: 'Erstes Licht',
    hint: 'Tippe den Spiegel an. Er kippt zwischen / und \\ – der Lichtfaden folgt sofort.',
    par: 1,
    rows: [
      '..o..',
      '.....',
      '>.\\..',
      '.....',
      '.....',
    ],
  },
  {
    id: 'l02',
    name: 'Doppelknoten',
    hint: 'Das Licht endet nicht am ersten Ziel – es läuft weiter. Ein Faden, zwei Punkte.',
    par: 2,
    rows: [
      '.o./.',
      '...o.',
      '>..\\.',
      '.....',
      '.....',
    ],
  },
  {
    id: 'l03',
    name: 'Schattenwurf',
    hint: 'Blocker verschlucken den Faden. Führe ihn außen herum.',
    par: 2,
    rows: [
      '..#...',
      '......',
      '>./...',
      '......',
      '../..o',
      '......',
    ],
  },
  {
    id: 'l04',
    name: 'Festgeschraubt',
    hint: 'Verschraubte Spiegel lassen sich nicht drehen. Plane mit ihnen statt gegen sie.',
    par: 2,
    rows: [
      '.\\o.2.',
      '......',
      '>...\\.',
      '......',
      '.o....',
      '......',
    ],
  },
  {
    id: 'l05',
    name: 'Serpentine',
    hint: 'Vier Kurven, drei Ziele. Denke den ganzen Weg, bevor du drehst.',
    par: 3,
    rows: [
      '.......',
      '.\\.o./.',
      '.......',
      '>....\\.',
      '.o.....',
      '.\\.o...',
      '.......',
    ],
  },
  {
    id: 'l06',
    name: 'Fadenkreuz',
    hint: 'Der Faden darf sich selbst kreuzen – dieselbe Zelle trägt zwei Richtungen.',
    par: 2,
    rows: [
      '.\\.o..',
      '......',
      '......',
      '>.../.',
      '.\\o./.',
      '......',
    ],
  },
  {
    id: 'l07',
    name: 'Schlinge',
    par: 3,
    rows: [
      '.\\../.',
      '....o.',
      '...o./',
      '...#..',
      '....\\/',
      '.^....',
    ],
  },
  {
    id: 'l08',
    name: 'Umlaufbahn',
    par: 3,
    rows: [
      '\\..\\...',
      '.......',
      '.......',
      '/..o.o2',
      '>..\\...',
      '.o..../',
    ],
  },
  {
    id: 'l09',
    name: 'Spindel',
    par: 4,
    rows: [
      '..\\.o./',
      '.......',
      '.....#.',
      '>../...',
      '..\\.o..',
      '.......',
      '...\\.o\\',
    ],
  },
  {
    id: 'l10',
    name: 'Schneckenhaus',
    par: 4,
    rows: [
      '/..o./##',
      'o#/....<',
      '/.../...',
      '........',
      '.....o..',
      '........',
      '..\\.\\...',
    ],
  },
  {
    id: 'l11',
    name: 'Webstuhl',
    hint: 'Vier Ziele, ein einziger Faden – er muss sie alle nacheinander aufsammeln.',
    par: 4,
    rows: [
      '.......',
      '...\\../',
      '...o..o',
      '>.../..',
      '/.../..',
      '\\..\\#..',
      '..o..o/',
    ],
  },
  {
    id: 'l12',
    name: 'Dämmerung',
    par: 5,
    rows: [
      '.\\.\\v...',
      '.....#..',
      '.o......',
      '........',
      '/...\\...',
      '\\o...o/.',
      '.../..\\.',
    ],
  },
  {
    id: 'l13',
    name: 'Flechtwerk',
    par: 5,
    rows: [
      '...\\.\\..',
      '\\.../...',
      '.#..o...',
      'o....o..',
      '..\\.....',
      '..o.\\/.<',
      '........',
      '\\..1....',
    ],
  },
  {
    id: 'l14',
    name: 'Zwielicht',
    par: 6,
    rows: [
      '.\\..../.',
      '........',
      '#o\\....<',
      '........',
      '........',
      '..\\\\o..2',
      './.\\..o.',
      '......\\\\',
    ],
  },
  {
    id: 'l15',
    name: 'Rankwerk',
    par: 6,
    rows: [
      './...o./',
      '.....\\.\\',
      '......o.',
      '>..\\.o..',
      '........',
      '/o.\\....',
      './..../.',
      '\\....\\..',
    ],
  },
  {
    id: 'l16',
    name: 'Flusslauf',
    hint: 'Das Feld wird weiter. Ein langer Faden holt Ziele, die weit auseinanderliegen.',
    par: 6,
    rows: [
      '.v.......',
      '\\.o.../..',
      '.....#\\./',
      '.........',
      '.........',
      '/.o....o.',
      '\\..o....\\',
      '2/.......',
    ],
  },
  {
    id: 'l17',
    name: 'Jahresringe',
    par: 7,
    rows: [
      './...../.',
      '......\\.<',
      '\\..o.....',
      '.........',
      '..../.o..',
      'o./.o.\\..',
      '../....\\.',
      '//.......',
    ],
  },
  {
    id: 'l18',
    name: 'Nordlicht',
    par: 7,
    rows: [
      '1/......',
      '........',
      '/o.o/...',
      '\\...\\.\\<',
      '........',
      '.o......',
      '\\......o',
      '.\\..o.\\.',
    ],
  },
  {
    id: 'l19',
    name: 'Spinnennetz',
    par: 7,
    rows: [
      '..\\...../',
      '.o.\\..#..',
      '..\\..../.',
      '......#..',
      '...o\\...o',
      '.\\......\\',
      '>....../.',
      '\\/.....#.',
      '\\o.\\.....',
    ],
  },
  {
    id: 'l20',
    name: 'Lichtkrone',
    par: 8,
    rows: [
      'o...../..',
      '.........',
      '.....\\./.',
      '..1..../.',
      '..\\.o.\\..',
      '../.....<',
      '../o..o./',
      '../.o.../',
      '../..\\...',
    ],
  },
];

export const levels = levelDefs.map(parseLevel);

export const levelById = new Map(levels.map((l) => [l.id, l]));
