// Levelsammlung.
//
// Textformat (siehe `level.js`):
//
//   .  leer          #  Blocker        o  Zielpunkt
//   >  < ^ v  Lichtquelle mit Strahlrichtung
//   /  \  drehbarer Spiegel            1  2  fester Spiegel („/“ bzw. „\“)
//   A  C  W  Knoten für Bernstein, Cyan, weißes Licht
//   p  q  drehbares Prisma             3  4  festes Prisma („/“ bzw. „\“)
//   _  leere Fassung – `prisms` sagt, wie viele Prismen im Vorrat liegen
//
// `par` ist die vom Solver bestimmte Mindestzahl an Zügen. Sie wird von
// `npm run check:lumen` gegengeprüft – ein falscher Wert ist ein Testfehler.

import { parseLevel } from './level.js';

export const levelDefs = [
  {
    id: 'l01',
    name: 'Erstes Licht',
    hint: 'Tippe den Spiegel an. Er kippt zwischen / und \\ – der Lichtfaden folgt sofort.',
    par: 1,
    rows: [
      '..o..',
      '.....',
      '>.\\..',
      '.....',
      '.....',
    ],
  },
  {
    id: 'l02',
    name: 'Doppelknoten',
    hint: 'Das Licht endet nicht am ersten Ziel – es läuft weiter. Ein Faden, zwei Punkte.',
    par: 2,
    rows: [
      '.o./.',
      '...o.',
      '>..\\.',
      '.....',
      '.....',
    ],
  },
  {
    id: 'l03',
    name: 'Schattenwurf',
    hint: 'Blocker verschlucken den Faden. Führe ihn außen herum.',
    par: 2,
    rows: [
      '..#...',
      '......',
      '>./...',
      '......',
      '../..o',
      '......',
    ],
  },
  {
    id: 'l04',
    name: 'Festgeschraubt',
    hint: 'Verschraubte Spiegel lassen sich nicht drehen. Plane mit ihnen statt gegen sie.',
    par: 2,
    rows: [
      '.\\o.2.',
      '......',
      '>...\\.',
      '......',
      '.o....',
      '......',
    ],
  },
  {
    id: 'l05',
    name: 'Serpentine',
    hint: 'Vier Kurven, drei Ziele. Denke den ganzen Weg, bevor du drehst.',
    par: 3,
    rows: [
      '.......',
      '.\\.o./.',
      '.......',
      '>....\\.',
      '.o.....',
      '.\\.o...',
      '.......',
    ],
  },
  {
    id: 'l06',
    name: 'Fadenkreuz',
    hint: 'Der Faden darf sich selbst kreuzen – dieselbe Zelle trägt zwei Richtungen.',
    par: 2,
    rows: [
      '.\\.o..',
      '......',
      '......',
      '>.../.',
      '.\\o./.',
      '......',
    ],
  },
  {
    id: 'l07',
    name: 'Schlinge',
    par: 3,
    rows: [
      '.\\../.',
      '....o.',
      '...o./',
      '...#..',
      '....\\/',
      '.^....',
    ],
  },
  {
    id: 'l08',
    name: 'Umlaufbahn',
    par: 3,
    rows: [
      '\\..\\...',
      '.......',
      '.......',
      '/..o.o2',
      '>..\\...',
      '.o..../',
    ],
  },
  {
    id: 'l09',
    name: 'Spindel',
    par: 4,
    rows: [
      '..\\.o./',
      '.......',
      '.....#.',
      '>../...',
      '..\\.o..',
      '.......',
      '...\\.o\\',
    ],
  },
  {
    id: 'l10',
    name: 'Schneckenhaus',
    par: 4,
    rows: [
      '/..o./##',
      'o#/....<',
      '/.../...',
      '........',
      '.....o..',
      '........',
      '..\\.\\...',
    ],
  },
  {
    id: 'l11',
    name: 'Webstuhl',
    hint: 'Vier Ziele, ein einziger Faden – er muss sie alle nacheinander aufsammeln.',
    par: 4,
    rows: [
      '.......',
      '...\\../',
      '...o..o',
      '>.../..',
      '/.../..',
      '\\..\\#..',
      '..o..o/',
    ],
  },
  {
    id: 'l12',
    name: 'Dämmerung',
    par: 5,
    rows: [
      '.\\.\\v...',
      '.....#..',
      '.o......',
      '........',
      '/...\\...',
      '\\o...o/.',
      '.../..\\.',
    ],
  },
  {
    id: 'l13',
    name: 'Flechtwerk',
    par: 5,
    rows: [
      '...\\.\\..',
      '\\.../...',
      '.#..o...',
      'o....o..',
      '..\\.....',
      '..o.\\/.<',
      '........',
      '\\..1....',
    ],
  },
  {
    id: 'l14',
    name: 'Zwielicht',
    par: 6,
    rows: [
      '.\\..../.',
      '........',
      '#o\\....<',
      '........',
      '........',
      '..\\\\o..2',
      './.\\..o.',
      '......\\\\',
    ],
  },
  {
    id: 'l15',
    name: 'Rankwerk',
    par: 6,
    rows: [
      './...o./',
      '.....\\.\\',
      '......o.',
      '>..\\.o..',
      '........',
      '/o.\\....',
      './..../.',
      '\\....\\..',
    ],
  },
  {
    id: 'l16',
    name: 'Flusslauf',
    hint: 'Das Feld wird weiter. Ein langer Faden holt Ziele, die weit auseinanderliegen.',
    par: 6,
    rows: [
      '.v.......',
      '\\.o.../..',
      '.....#\\./',
      '.........',
      '.........',
      '/.o....o.',
      '\\..o....\\',
      '2/.......',
    ],
  },
  {
    id: 'l17',
    name: 'Jahresringe',
    par: 7,
    rows: [
      './...../.',
      '......\\.<',
      '\\..o.....',
      '.........',
      '..../.o..',
      'o./.o.\\..',
      '../....\\.',
      '//.......',
    ],
  },
  {
    id: 'l18',
    name: 'Nordlicht',
    par: 7,
    rows: [
      '1/......',
      '........',
      '/o.o/...',
      '\\...\\.\\<',
      '........',
      '.o......',
      '\\......o',
      '.\\..o.\\.',
    ],
  },
  {
    id: 'l19',
    name: 'Spinnennetz',
    par: 7,
    rows: [
      '..\\...../',
      '.o.\\..#..',
      '..\\..../.',
      '......#..',
      '...o\\...o',
      '.\\......\\',
      '>....../.',
      '\\/.....#.',
      '\\o.\\.....',
    ],
  },
  {
    id: 'l20',
    name: 'Lichtkrone',
    par: 8,
    rows: [
      'o...../..',
      '.........',
      '.....\\./.',
      '..1..../.',
      '..\\.o.\\..',
      '../.....<',
      '../o..o./',
      '../.o.../',
      '../..\\...',
    ],
  },
  {
    id: 'l21',
    name: 'Zweifarbig',
    teach: {
      id: 'prisma',
      title: 'Das Prisma',
      body: 'Ein Prisma trennt das Licht: Bernstein läuft geradeaus hindurch, Cyan wird um 90° abgelenkt – genau wie an einem Spiegel derselben Lage. Aus einem weißen Faden werden so zwei, und jeder will seinen eigenen Weg.',
    },
    par: 3,
    rows: [
      '.........',
      '..\\.../..',
      '.........',
      '>.3...../',
      '.........',
      '....o./.o',
      '.........',
    ],
  },
  {
    id: 'l22',
    name: 'Bernsteinpfad',
    teach: {
      id: 'farbe',
      title: 'Farbige Knoten',
      body: 'Ein Bernsteinknoten leuchtet nur in reinem Bernstein, ein Cyanknoten nur in reinem Cyan. Weißes Licht ist ihnen zu grell – erst hinter dem Prisma ist der Faden sauber genug.',
    },
    par: 4,
    rows: [
      '..v......',
      '....C../.',
      '.........',
      '..4....\\.',
      '..../....',
      '......A..',
      '../...\\..',
      '.........',
    ],
  },
  {
    id: 'l23',
    name: 'Wiedervereint',
    hint: 'Verlassen Bernstein und Cyan dasselbe Prisma in derselben Richtung, ist das Licht dahinter wieder weiß.',
    par: 5,
    rows: [
      '.......',
      '.......',
      '..\\../W',
      '.....C.',
      '>.3.//3',
      '....A..',
      '....\\.\\',
    ],
  },
  {
    id: 'l24',
    name: 'Die Fassung',
    teach: {
      id: 'fassung',
      title: 'Die Fassung',
      body: 'Eine leere Fassung ist für das Licht nicht vorhanden. Tippe sie an, und ein Prisma aus dem Vorrat rastet ein; der nächste Tipp dreht es, der übernächste nimmt es wieder heraus. Es liegen weniger Prismen bereit, als Fassungen da sind – such dir die richtige aus.',
    },
    prisms: 1,
    par: 5,
    rows: [
      '.........',
      '.C.......',
      '.........',
      '>._._._./',
      '.........',
      './..\\...A',
      '.........',
    ],
  },
  {
    id: 'l25',
    name: 'Scherenschnitt',
    hint: 'Die Blocker lassen nur einer Fassung beide Farbwege offen.',
    prisms: 1,
    par: 6,
    rows: [
      '.........',
      '.C..#.A./',
      '..##.....',
      '>.__.__.\\',
      '..#...#..',
      './...\\...',
    ],
  },
  {
    id: 'l26',
    name: 'Doppelnaht',
    hint: 'Zwei Prismen im Vorrat: Das erste trennt den Faden, das zweite näht ihn wieder zusammen.',
    prisms: 2,
    par: 7,
    rows: [
      '..\\._C/.',
      '........',
      '........',
      '>._A.__/',
      '.......W',
      '.....W.\\',
    ],
  },
  {
    id: 'l27',
    name: 'Wendeglas',
    hint: 'Auch ein Prisma lässt sich drehen – nur versetzen kann man es nicht.',
    par: 8,
    rows: [
      '.........',
      '>.p.A.q./',
      '.........',
      '.........',
      '../C/....',
      '..W.....\\',
      '..../.\\..',
    ],
  },
  {
    id: 'l28',
    name: 'Nadelöhr',
    prisms: 1,
    par: 9,
    rows: [
      '>.4./....',
      '.\\....../',
      '....A....',
      '../C../._',
      '.........',
      '......_..',
      '.W../__o\\',
    ],
  },
  {
    id: 'l29',
    name: 'Buntgewebe',
    prisms: 2,
    par: 10,
    rows: [
      '.........',
      '>._._./..',
      '.\\..W....',
      '......A..',
      '.._......',
      '......_./',
      '.........',
      '../C....\\',
      './..o.\\..',
    ],
  },
  {
    id: 'l30',
    name: 'Weberknoten',
    hint: 'Trennen, weit auseinanderführen, wieder zusammenbringen – und unterwegs nichts verlieren.',
    prisms: 2,
    par: 11,
    rows: [
      '>._..._./',
      '.o../....',
      '....W...A',
      '.._.....3',
      '.\\...o_.\\',
      '.........',
      '../C..3..',
      '.........',
      './..\\....',
    ],
  },
];

export const levels = levelDefs.map(parseLevel);

export const levelById = new Map(levels.map((l) => [l.id, l]));
